### ISSUE TITLE
Feature request: add a switch

### ISSUE THREAD

**Issue by Stuermer** [ShellAddicted/plasmoid-pihole-unofficial#1]
Great plugin, works fine! 
It would be great to have a button to switch pihole off. Ideally in the task menu. I saw a comment somewhere that it was / is planned to be added? Unfortunately I have no experience with QML. 
Also, making it available under https://store.kde.org/ might make people more aware of the plugin?

**Comment by ShellAddicted** [comment]
@Stuermer Thanks! yes it is planned but I developed this for personal use, and I don't really need that button. so it's a low priority task for me, I will work on that when I have some free time.
